name = "ExponentialFamily"
uuid = "62312e5e-252a-4322-ace9-a5f4bf9b357b"
authors = ["Ismail Senoz"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
